{{- template "common.deployment" (list . "sample-app.deployment") -}}
{{- define "sample-app.deployment" -}}
## Define overrides for your Deployment resource here, e.g.
spec:
  template:
    spec:
      containers:
      - {{ template "common.container" (list . "sample-app.deployment.container") }}
{{- end -}}
{{- define "sample-app.deployment.container" -}}
## Define overrides for your Container here, e.g.
livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80
{{- end -}}